# Generated by Django 4.2.24 on 2025-09-29 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('retell_conversation_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('retell_call_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('twilio_call_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('whatsapp_msg_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('external_ref', models.CharField(blank=True, help_text='ID externo adicional (si aplica)', max_length=128, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('voice', 'Voz (Retell)'), ('web', 'Web/Chat')], max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('failed', 'Fallida'), ('missed', 'Perdida/No contestada'), ('canceled', 'Cancelada'), ('ongoing', 'En curso')], default='ongoing', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='es', help_text='código ISO (es, en, etc.)', max_length=12)),
                ('intent', models.CharField(blank=True, help_text='intención/dominio detectado', max_length=64, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('from_identity', models.CharField(blank=True, help_text='quién inicia (tel/JID)', max_length=128, null=True)),
                ('to_identity', models.CharField(blank=True, help_text='destino (tel/JID)', max_length=128, null=True)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_completion', models.PositiveIntegerField(default=0)),
                ('voice_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transcription_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transcript_excerpt', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='CommMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('voice', 'Voz (Retell)'), ('web', 'Web/Chat')], max_length=16)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente (IA)'), ('agent', 'Agente Humano'), ('system', 'Sistema')], max_length=16)),
                ('content', models.TextField(blank=True, null=True)),
                ('provider_msg_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('has_attachments', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.commsession')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CommAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('attach_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Imagen'), ('document', 'Documento'), ('other', 'Otro')], default='audio', max_length=16)),
                ('storage_path', models.CharField(help_text='ruta/URL al archivo (S3, etc.)', max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.commmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='commsession',
            index=models.Index(fields=['tenant', 'started_at'], name='communicati_tenant_4e7685_idx'),
        ),
        migrations.AddIndex(
            model_name='commsession',
            index=models.Index(fields=['tenant', 'channel', 'started_at'], name='communicati_tenant_a0cc40_idx'),
        ),
        migrations.AddIndex(
            model_name='commsession',
            index=models.Index(fields=['tenant', 'status'], name='communicati_tenant_0daf98_idx'),
        ),
        migrations.AddIndex(
            model_name='commsession',
            index=models.Index(fields=['tenant', 'user', 'started_at'], name='communicati_tenant_5e5e43_idx'),
        ),
        migrations.AddIndex(
            model_name='commmessage',
            index=models.Index(fields=['tenant', 'timestamp'], name='communicati_tenant_10f901_idx'),
        ),
        migrations.AddIndex(
            model_name='commmessage',
            index=models.Index(fields=['tenant', 'session', 'timestamp'], name='communicati_tenant_bea55f_idx'),
        ),
        migrations.AddIndex(
            model_name='commmessage',
            index=models.Index(fields=['tenant', 'role'], name='communicati_tenant_97ae42_idx'),
        ),
        migrations.AddIndex(
            model_name='commattachment',
            index=models.Index(fields=['tenant', 'attach_type'], name='communicati_tenant_927e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='commattachment',
            index=models.Index(fields=['tenant', 'created_at'], name='communicati_tenant_a9724b_idx'),
        ),
    ]
