# Generated by Django 4.2.24 on 2025-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_commsession_commmessage_commattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsession',
            name='conversation_flow_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='commsession',
            name='provider',
            field=models.CharField(db_index=True, default='retell', max_length=32),
        ),
        migrations.AddField(
            model_name='commsession',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
