# Generated by Django 4.2.24 on 2025-10-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0005_conversation_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='communicati_user_id_3fab42_idx',
            old_name='communicati_user_id_ended_a1e0e8_idx',
        ),
        migrations.AddField(
            model_name='conversationmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['user'], name='communicati_user_id_8a05f1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['last_updated'], name='communicati_last_up_00dceb_idx'),
        ),
    ]
