# Generated by Django 4.2.24 on 2025-09-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_ext', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='accounts_ex_user_id_66573c_idx',
            old_name='accounts_ext_user_idx',
        ),
    ]
